name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      # CAMBIAMOS ESTA LÍNEA: De 'npm ci' a 'npm install'
      - run: npm install
      
      - run: npm run build
        env:
          VITE_API_BASE_URL: https://service.andromeda.andrescortes.dev
          VITE_MEDIA_BASE_URL: https://admin.andromeda.andrescortes.dev/storage
